#!/bin/bash

AIRPORTS="ATL"
AIRPORTS+=" BOS"
AIRPORTS+=" DCA"
AIRPORTS+=" DEN"
AIRPORTS+=" DFW"
AIRPORTS+=" EWR"
AIRPORTS+=" IAD"
AIRPORTS+=" IAH"
AIRPORTS+=" JAX"
AIRPORTS+=" JFK"
AIRPORTS+=" LAX"
AIRPORTS+=" MCO"
AIRPORTS+=" MIA"
AIRPORTS+=" ORD"
AIRPORTS+=" PHX"
AIRPORTS+=" SEA"
AIRPORTS+=" SFO"
AIRPORTS+=" TPA"
AIRPORTS+=" YEG"
AIRPORTS+=" YHG"
AIRPORTS+=" YOW"
AIRPORTS+=" YUL"
AIRPORTS+=" YVR"
AIRPORTS+=" YWG"
AIRPORTS+=" YYC"
AIRPORTS+=" YYZ"

for CODE in ${AIRPORTS}; do
  LOCATION="${CODE}" ./bash_search.sh
  echo
done
